apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      containers:
      - name: app
        image: google/cloud-sdk
        command: ["gsutil", "-m", "rsync", "-r", "gs://example-bucket", "/data/input"]
        volumeMounts:
        - name: data-disk
          mountPath: /data/input
      volumes:
      - name: data-disk
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
      restartPolicy: OnFailure