apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi